import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Banner from "../components/Banner";
import Largecard from "../components/Largecard";
import Footer from "../components/Footer";
import Smallcard from "../components/Smallcard";
import Mediumcard from "../components/Mediumcard";

export default function Home() {
  
  
  return (
    <div className="bg-black">
      <Head>
        <title>AirBnB 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16 ">
        <Smallcard/>
        <Mediumcard/>
        <Largecard/>
        <Footer/>
      </main>
    </div>
  );
}
